// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ainmbbtycciukbjjdjtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpbm1iYnR5Y2NpdWtiampkanRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjkyOTgsImV4cCI6MjA2Mzk0NTI5OH0.MpfLyOdcRVv-rFrX-mCHemLjaDx6hzHU_nH9kUfEqpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);